import type { Metadata } from "next";
import {
  ArrowDown,
  ArrowRight,
  CircleAlert,
  Database,
  Laptop,
  Radio,
  Server,
} from "lucide-react";
import Link from "next/link";
import { EditorialHero } from "@/components/editorial-hero";
import { StatusBadge } from "@/components/status-badge";

export const metadata: Metadata = {
  title: "QGPS Integration",
  description:
    "Review the current simulated QGPS boundary, normalized data contract, states, and requirements for a verified live integration.",
};

const registry = [
  ["Exact project", "Pending client confirmation"],
  ["Repository and version", "Not supplied"],
  ["License", "Not supplied"],
  ["Protocol / transport", "Not supplied"],
  ["Supported payload", "Not verified"],
] as const;

const fields = [
  ["position", "Latitude, longitude, altitude, and original fix time"],
  ["quality", "Horizontal accuracy, fix type, satellites, and HDOP when supplied"],
  ["track", "Ordered recent points with original timestamps"],
  ["connection", "Connected, offline, or unavailable transport state"],
  ["provenance", "Adapter, upstream project, protocol, and schema version"],
] as const;

export default function QgpsPage() {
  return (
    <>
      <EditorialHero
        eyebrow="QGPS Integration"
        title={
          <>
            Position data, <em>without false certainty.</em>
          </>
        }
        description="Catalyst places a backend boundary between the browser and QGPS, normalizes the payload, and presents its age and quality alongside the position. The live upstream remains unconfirmed."
        image="/images/catalyst-hero.png"
        imageAlt="Mountaineers moving along a remote snow ridge beneath a dark sky"
        actions={
          <Link className="button button--primary" href="/demo">
            Open simulated demo <ArrowRight aria-hidden="true" />
          </Link>
        }
      />

      <section className="integration-status shell" aria-labelledby="integration-status-title">
        <div className="integration-status__summary">
          <StatusBadge tone="warning">Partial · simulated only</StatusBadge>
          <p className="eyebrow">Milestone 1 integration status</p>
          <h2 id="integration-status-title">The interface is testable. The upstream is not identified.</h2>
          <p>
            No exact QGPS project, backend implementation, API contract, license, or sample payload
            is present in the supplied repositories. Choosing one of several unrelated public projects
            would fabricate the dependency.
          </p>
        </div>
        <div className="integration-status__alert">
          <CircleAlert aria-hidden="true" />
          <div>
            <strong>Not a completed live integration</strong>
            <p>
              Every demo payload is generated by a same-origin Catalyst fixture and is visibly marked
              <span className="inline-data"> SIMULATED</span>.
            </p>
          </div>
        </div>
      </section>

      <section className="architecture-section">
        <div className="shell">
          <div className="section-heading">
            <p className="eyebrow">Required architecture</p>
            <h2>The browser never speaks to QGPS directly.</h2>
            <p>
              Authentication, protocol handling, normalization, retry policy, and source metadata
              belong behind the Catalyst backend boundary.
            </p>
          </div>
          <ol className="architecture-flow" aria-label="QGPS data flow">
            <li>
              <Laptop aria-hidden="true" />
              <span>01</span>
              <h3>Web interface</h3>
              <p>Requests a normalized snapshot from the same-origin Catalyst route.</p>
            </li>
            <ArrowDown className="architecture-flow__arrow" aria-hidden="true" />
            <li>
              <Server aria-hidden="true" />
              <span>02</span>
              <h3>Catalyst backend</h3>
              <p>Validates access, adapts the upstream protocol, and preserves provenance.</p>
            </li>
            <ArrowDown className="architecture-flow__arrow" aria-hidden="true" />
            <li data-unavailable="true">
              <Radio aria-hidden="true" />
              <span>03</span>
              <h3>QGPS source</h3>
              <p>Unavailable until the client identifies the exact project and deployment.</p>
            </li>
          </ol>
        </div>
      </section>

      <section className="source-register shell">
        <div className="source-register__heading">
          <p className="eyebrow">Upstream register</p>
          <h2>Confirmation required before connection.</h2>
          <p>
            These fields are intentionally unresolved. A literal-name match is not sufficient evidence
            to select a dependency for operational position data.
          </p>
        </div>
        <dl className="source-register__list">
          {registry.map(([label, value]) => (
            <div key={label}>
              <dt>{label}</dt>
              <dd>{value}</dd>
            </div>
          ))}
        </dl>
      </section>

      <section className="normalized-contract">
        <div className="shell normalized-contract__grid">
          <div>
            <Database aria-hidden="true" />
            <p className="eyebrow">Normalized contract</p>
            <h2>Stable for the interface. Nullable at the source.</h2>
            <p>
              The demo uses a provider-neutral snapshot so the UI can be built and tested without
              pretending that every upstream supplies the same precision or fields.
            </p>
            <div className="contract-version">
              <span>Schema</span>
              <strong>catalyst.qgps.snapshot.v1</strong>
            </div>
          </div>
          <dl className="contract-fields">
            {fields.map(([name, description]) => (
              <div key={name}>
                <dt>{name}</dt>
                <dd>{description}</dd>
              </div>
            ))}
          </dl>
        </div>
      </section>

      <section className="state-semantics shell">
        <div className="section-heading">
          <p className="eyebrow">Data semantics</p>
          <h2>One label for what the data is. Another for how old it is.</h2>
        </div>
        <div className="state-semantics__grid">
          <article>
            <StatusBadge tone="information">Live</StatusBadge>
            <h3>Verified live source</h3>
            <p>Used only when a confirmed upstream and declared freshness window both pass.</p>
          </article>
          <article>
            <StatusBadge tone="simulated">Simulated</StatusBadge>
            <h3>Fixture-generated</h3>
            <p>The current demo mode. It can look current but it can never be labeled live.</p>
          </article>
          <article>
            <StatusBadge tone="warning">Stale</StatusBadge>
            <h3>Outside threshold</h3>
            <p>The last-known point remains visible with its age and a muted map marker.</p>
          </article>
          <article>
            <StatusBadge tone="unknown">Offline</StatusBadge>
            <h3>Connection lost</h3>
            <p>Transport is offline; preserved data stays explicitly last-known.</p>
          </article>
          <article>
            <StatusBadge tone="critical">Unavailable</StatusBadge>
            <h3>No usable source</h3>
            <p>No position is presented as current, and the missing dependency stays visible.</p>
          </article>
        </div>
      </section>

      <section className="confirmation-list shell">
        <div>
          <p className="eyebrow">Needed from the client</p>
          <h2>Evidence required to move from simulated to live.</h2>
        </div>
        <ol>
          <li>Exact QGPS project URL, repository, and deployed version</li>
          <li>License and permission for the intended pilot use</li>
          <li>Transport specification, sample payloads, and authentication method</li>
          <li>Deployment topology, device model, and update cadence</li>
          <li>Field definitions, units, accuracy semantics, and freshness thresholds</li>
        </ol>
      </section>

      <section className="simple-cta shell">
        <p className="eyebrow">Inspect the behavior</p>
        <h2>Test the interface before the source arrives.</h2>
        <p>Switch between current fixture, stale, offline, empty, error, and unavailable states.</p>
        <Link className="button button--primary" href="/demo">
          Open simulated demo <ArrowRight aria-hidden="true" />
        </Link>
      </section>
    </>
  );
}
